# Generated by Django 2.2.12 on 2020-04-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedRelationsModel',
            fields=[
                ('hash_id', models.AutoField(primary_key=True, serialize=False)),
                ('joined_field', models.IntegerField()),
                ('field1', models.IntegerField()),
                ('field2', models.IntegerField()),
                ('field3', models.IntegerField()),
                ('field4', models.IntegerField()),
                ('field5', models.IntegerField()),
                ('field6', models.IntegerField()),
            ],
        ),
    ]
