# Generated by Django 2.2.12 on 2020-04-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedrelationsmodel',
            name='hash_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
